name: build

on:
  workflow_dispatch:
  pull_request:

jobs:
  cargo_build:
    name: cargo build
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - uses: dtolnay/rust-toolchain@stable
      - name: apt-get install
        run: |
          sudo apt-get update
          sudo apt-get install -y libwebkit2gtk-4.1-dev
      - run: cargo build

  build_android:
    name: build Android plugin
    runs-on: ubuntu-latest
    needs: cargo_build
    defaults:
      run:
        working-directory: ./android

    steps:
      - uses: actions/checkout@v4
      - run: ./gradlew build

  build_ios:
    name: build iOS plugin
    runs-on: ubuntu-latest
    needs: cargo_build
    defaults:
      run:
        working-directory: ./ios

    steps:
      - uses: actions/checkout@v4
      - uses: swift-actions/setup-swift@v2
      - run: swift build
