name: publish --dry-run

on:
  workflow_dispatch:

jobs:
  publish_crates_io:
    name: publish (crates.io) --dry-run
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - uses: dtolnay/rust-toolchain@stable
      - name: apt-get install
        run: |
          sudo apt-get update
          sudo apt-get install -y libwebkit2gtk-4.1-dev
      - name: cargo publish
        run: cargo publish --dry-run
        env:
          CARGO_REGISTRY_TOKEN: ${{ secrets.CARGO_REGISTRY_TOKEN }}

  publish_npmjs_com:
    name: publish (npmjs.com) --dry-run
    runs-on: ubuntu-latest
    permissions:
      id-token: write # use of OIDC for npm provenance

    steps:
      - uses: actions/checkout@v4
      - uses: pnpm/action-setup@v4
        with:
          version: 9
      - uses: actions/setup-node@v4
        with:
          node-version: "lts/*"
          registry-url: "https://registry.npmjs.org"
          cache: "pnpm"
      - run: pnpm install
      - name: pnpm publish
        run: pnpm publish --access public --no-git-checks --dry-run
        env:
          NPM_CONFIG_PROVENANCE: true
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
